# -*- coding: utf-8 -*-
"""Shrey-Simulation-Clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3vEezKj2I3xWspeUVXpQ1vD2hdvjQck
"""

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
# from google.colab import files  # Uncomment if running in Colab

print("SHREY YADAV | HONEST SIMULATION | github.com/shreyyadav25/economics-rp-2026")

# TRUE DGP PARAMETERS (EXPLICITLY BAKED IN)
true_beta_low_skill = -0.120
true_beta_high_skill = 0.042
tau_mean = 0.20
tau_sd = 0.15

np.random.seed(42)
n = 100000

print("Generating synthetic microdata...")
df = pd.DataFrame({
    'year': np.random.choice([2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026], n),
    'ai_exposure': np.clip(np.random.normal(tau_mean, tau_sd, n), 0, 1),
    'college': np.random.choice([0, 1], n, p=[0.65, 0.35])
})

df['post'] = (df['year'] >= 2024).astype(int)
df['log_wage'] = (true_beta_low_skill * df['ai_exposure'] * df['post'] * (1 - df['college']) +
                  true_beta_high_skill * df['ai_exposure'] * df['post'] * df['college'] +
                  np.random.normal(0, 0.3, n))

print("True DGP:")
print(f" Low-skill AI×Post: {true_beta_low_skill}")
print(f" High-skill AI×Post: {true_beta_high_skill}")

# RECOVER PARAMETERS
model_full = smf.ols('log_wage ~ ai_exposure * post * C(college)', data=df).fit()
model_simple = smf.ols('log_wage ~ ai_exposure * post + C(college)', data=df).fit()

print("\nRECOVERED:")
print(f"Full model low-skill: {model_full.params['ai_exposure:post:C(college)[T.1]']:.3f}")
print(f"Full model high-skill: {model_full.params['ai_exposure:post']:.3f}")
print(f"Simple model: {model_simple.params['ai_exposure:post']:.3f}")

# EXPORT ALL
df.to_csv('simulated_microdata_100k.csv', index=False)
results = pd.DataFrame({
    'specification': ['true_dgp_low', 'true_dgp_high', 'recovered_simple', 'recovered_full_low', 'recovered_full_high'],
    'beta': [true_beta_low_skill, true_beta_high_skill,
             model_simple.params['ai_exposure:post'],
             model_full.params['ai_exposure:post'],
             model_full.params['ai_exposure:post:C(college)[T.1]']],
    'se': [0, 0,
           model_simple.bse['ai_exposure:post'],
           model_full.bse['ai_exposure:post'],
           model_full.bse['ai_exposure:post:C(college)[T.1]']],
    'N': [n]*5
})
results.to_csv('simulation_results.csv', index=False)

# Uncomment these lines if running in Google Colab:
# files.download('simulated_microdata_100k.csv')
# files.download('simulation_results.csv')
print("\nFiles saved: simulated_microdata_100k.csv + simulation_results.csv")
print(results.round(3))